# -*- coding: utf-8 -*-
"""Activity_2_Tyler_Fuller.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YZxBQvETNIReQqa8UXpELSKVa5e0_nIo
"""

# User input width and height
width = float(input("Enter width "))
height = float(input("Enter height "))

# Compute area
area = width*height

# Output area to the console
print(f"Area is {area} square units")